
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `groups_area_list_view`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `groups_area_list_view` (
  `groups_area_list_views_id` bigint(20) DEFAULT NULL,
  `list_view_id` bigint(20) DEFAULT NULL,
  KEY `FKCFD9663FB85CB193` (`list_view_id`),
  KEY `FKCFD9663FFF0AEF7B` (`groups_area_list_views_id`),
  CONSTRAINT `FKCFD9663FB85CB193` FOREIGN KEY (`list_view_id`) REFERENCES `list_view` (`id`),
  CONSTRAINT `FKCFD9663FFF0AEF7B` FOREIGN KEY (`groups_area_list_views_id`) REFERENCES `groups_area` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `groups_area_list_view` WRITE;
/*!40000 ALTER TABLE `groups_area_list_view` DISABLE KEYS */;
INSERT INTO `groups_area_list_view` VALUES (71,250);
INSERT INTO `groups_area_list_view` VALUES (71,249);
INSERT INTO `groups_area_list_view` VALUES (71,246);
INSERT INTO `groups_area_list_view` VALUES (65,201);
INSERT INTO `groups_area_list_view` VALUES (72,201);
INSERT INTO `groups_area_list_view` VALUES (73,246);
INSERT INTO `groups_area_list_view` VALUES (68,201);
INSERT INTO `groups_area_list_view` VALUES (69,272);
INSERT INTO `groups_area_list_view` VALUES (69,270);
INSERT INTO `groups_area_list_view` VALUES (69,213);
INSERT INTO `groups_area_list_view` VALUES (69,268);
INSERT INTO `groups_area_list_view` VALUES (69,215);
INSERT INTO `groups_area_list_view` VALUES (69,271);
INSERT INTO `groups_area_list_view` VALUES (76,250);
INSERT INTO `groups_area_list_view` VALUES (76,249);
INSERT INTO `groups_area_list_view` VALUES (76,246);
INSERT INTO `groups_area_list_view` VALUES (78,201);
INSERT INTO `groups_area_list_view` VALUES (79,249);
INSERT INTO `groups_area_list_view` VALUES (79,250);
INSERT INTO `groups_area_list_view` VALUES (79,246);
INSERT INTO `groups_area_list_view` VALUES (80,272);
INSERT INTO `groups_area_list_view` VALUES (80,268);
INSERT INTO `groups_area_list_view` VALUES (80,271);
INSERT INTO `groups_area_list_view` VALUES (80,270);
INSERT INTO `groups_area_list_view` VALUES (80,213);
INSERT INTO `groups_area_list_view` VALUES (80,215);
INSERT INTO `groups_area_list_view` VALUES (81,222);
INSERT INTO `groups_area_list_view` VALUES (63,201);
INSERT INTO `groups_area_list_view` VALUES (64,213);
INSERT INTO `groups_area_list_view` VALUES (64,215);
INSERT INTO `groups_area_list_view` VALUES (64,272);
INSERT INTO `groups_area_list_view` VALUES (64,270);
INSERT INTO `groups_area_list_view` VALUES (64,271);
INSERT INTO `groups_area_list_view` VALUES (64,268);
INSERT INTO `groups_area_list_view` VALUES (84,198);
INSERT INTO `groups_area_list_view` VALUES (84,196);
INSERT INTO `groups_area_list_view` VALUES (84,195);
INSERT INTO `groups_area_list_view` VALUES (85,196);
INSERT INTO `groups_area_list_view` VALUES (85,198);
INSERT INTO `groups_area_list_view` VALUES (85,195);
INSERT INTO `groups_area_list_view` VALUES (86,201);
INSERT INTO `groups_area_list_view` VALUES (87,249);
INSERT INTO `groups_area_list_view` VALUES (87,246);
INSERT INTO `groups_area_list_view` VALUES (87,250);
INSERT INTO `groups_area_list_view` VALUES (89,222);
INSERT INTO `groups_area_list_view` VALUES (90,196);
INSERT INTO `groups_area_list_view` VALUES (90,198);
INSERT INTO `groups_area_list_view` VALUES (90,195);
INSERT INTO `groups_area_list_view` VALUES (91,196);
INSERT INTO `groups_area_list_view` VALUES (91,198);
INSERT INTO `groups_area_list_view` VALUES (91,195);
INSERT INTO `groups_area_list_view` VALUES (92,201);
INSERT INTO `groups_area_list_view` VALUES (96,196);
INSERT INTO `groups_area_list_view` VALUES (96,195);
INSERT INTO `groups_area_list_view` VALUES (96,198);
INSERT INTO `groups_area_list_view` VALUES (97,196);
INSERT INTO `groups_area_list_view` VALUES (97,198);
INSERT INTO `groups_area_list_view` VALUES (97,195);
INSERT INTO `groups_area_list_view` VALUES (98,201);
INSERT INTO `groups_area_list_view` VALUES (99,249);
INSERT INTO `groups_area_list_view` VALUES (99,250);
INSERT INTO `groups_area_list_view` VALUES (99,246);
INSERT INTO `groups_area_list_view` VALUES (100,272);
INSERT INTO `groups_area_list_view` VALUES (100,271);
INSERT INTO `groups_area_list_view` VALUES (100,268);
INSERT INTO `groups_area_list_view` VALUES (100,213);
INSERT INTO `groups_area_list_view` VALUES (100,270);
INSERT INTO `groups_area_list_view` VALUES (100,215);
INSERT INTO `groups_area_list_view` VALUES (101,222);
INSERT INTO `groups_area_list_view` VALUES (70,222);
INSERT INTO `groups_area_list_view` VALUES (70,223);
INSERT INTO `groups_area_list_view` VALUES (70,224);
INSERT INTO `groups_area_list_view` VALUES (70,221);
INSERT INTO `groups_area_list_view` VALUES (70,273);
INSERT INTO `groups_area_list_view` VALUES (77,222);
INSERT INTO `groups_area_list_view` VALUES (77,273);
INSERT INTO `groups_area_list_view` VALUES (77,223);
INSERT INTO `groups_area_list_view` VALUES (77,221);
INSERT INTO `groups_area_list_view` VALUES (77,224);
INSERT INTO `groups_area_list_view` VALUES (66,268);
INSERT INTO `groups_area_list_view` VALUES (66,215);
INSERT INTO `groups_area_list_view` VALUES (66,272);
INSERT INTO `groups_area_list_view` VALUES (66,270);
INSERT INTO `groups_area_list_view` VALUES (66,271);
INSERT INTO `groups_area_list_view` VALUES (66,213);
INSERT INTO `groups_area_list_view` VALUES (66,291);
INSERT INTO `groups_area_list_view` VALUES (64,291);
INSERT INTO `groups_area_list_view` VALUES (69,291);
INSERT INTO `groups_area_list_view` VALUES (74,291);
INSERT INTO `groups_area_list_view` VALUES (80,291);
INSERT INTO `groups_area_list_view` VALUES (100,291);
INSERT INTO `groups_area_list_view` VALUES (80,307);
INSERT INTO `groups_area_list_view` VALUES (66,307);
INSERT INTO `groups_area_list_view` VALUES (88,307);
INSERT INTO `groups_area_list_view` VALUES (88,270);
INSERT INTO `groups_area_list_view` VALUES (88,213);
INSERT INTO `groups_area_list_view` VALUES (88,215);
INSERT INTO `groups_area_list_view` VALUES (88,268);
INSERT INTO `groups_area_list_view` VALUES (88,271);
INSERT INTO `groups_area_list_view` VALUES (88,272);
INSERT INTO `groups_area_list_view` VALUES (88,291);
INSERT INTO `groups_area_list_view` VALUES (103,313);
INSERT INTO `groups_area_list_view` VALUES (103,316);
/*!40000 ALTER TABLE `groups_area_list_view` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

